let chatThreads=[],chatUsers=[],activeChatId=0,chatMessages=[],chatAttachment=null,chatPollTimer=null,chatNotificationReady=false;
const chatUnreadState=new Map(),chatNotificationsKey='pqm.chatNotifications';
function chatNotificationsEnabled(){try{return localStorage.getItem(chatNotificationsKey)!=='off'}catch{return true}}
function updateChatNotificationButton(){const button=$('#chatNotificationToggle'),status=$('#chatNotificationStatus');if(!button||!status)return;if(!('Notification'in window)){button.disabled=true;button.textContent='Не підтримується';status.textContent='Цей браузер не підтримує системні сповіщення.';return}const permission=Notification.permission,enabled=chatNotificationsEnabled();button.disabled=false;button.textContent=permission==='granted'&&enabled?'Вимкнути системні сповіщення':'Увімкнути системні сповіщення';status.textContent=permission==='granted'&&enabled?'Системні сповіщення увімкнено.':'Внутрішні сповіщення PQM працюють; системні вимкнено.'}
function notifyNewChatMessage(chat){if(activeModule==='messages'&&activeChatId===chat.id&&document.visibilityState==='visible')return;const sender=(chat.members||[]).find(user=>user.username===chat.last_sender),title=chat.is_group?chatTitle(chat):chatUserLabel(sender),body=chat.last_body||'Нове повідомлення з вкладенням або заявкою';toast(`Нове повідомлення · ${title}`);if(!('Notification'in window)||Notification.permission!=='granted'||!chatNotificationsEnabled())return;const notice=new Notification(`PQM · ${title}`,{body,icon:'assets/profzakupivli-favicon.webp',tag:`pqm-chat-${chat.id}`,renotify:true});notice.onclick=()=>{window.focus();showModule('messages');openChat(chat.id);notice.close()}}
const chatNotificationSettings=document.createElement('section');chatNotificationSettings.className='account-notification-settings';chatNotificationSettings.innerHTML='<div><strong>Сповіщення про нові повідомлення</strong><small id="chatNotificationStatus"></small></div><button id="chatNotificationToggle" class="ghost" type="button">Увімкнути системні сповіщення</button>';$('#accountPasswordFields').before(chatNotificationSettings);updateChatNotificationButton();$('#chatNotificationToggle').onclick=async()=>{if(!('Notification'in window))return;if(Notification.permission==='granted'){try{localStorage.setItem(chatNotificationsKey,chatNotificationsEnabled()?'off':'on')}catch{}}else{const permission=await Notification.requestPermission();if(permission==='granted')try{localStorage.setItem(chatNotificationsKey,'on')}catch{};if(permission==='denied')toast('Браузер заблокував системні сповіщення. Дозвіл можна змінити в налаштуваннях сайту.')}updateChatNotificationButton()};
function chatUserLabel(user){return user?.display_name||user?.username||'Користувач'}
function chatTitle(chat){if(chat.title)return chat.title;const peer=(chat.members||[]).find(user=>user.username!==currentAuthUser);return chatUserLabel(peer)||'Особистий чат'}
function chatPresence(user){return user?.online?'Онлайн':presenceLabels[user?.presence_status]||'Офлайн'}
function chatInitials(user){return chatUserLabel(user).split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toLocaleUpperCase('uk-UA')||'●'}
function chatAvatar(user,group=false){if(group)return '<img class="chat-avatar" src="assets/group-avatar.svg" alt="Груповий чат">';if(user?.has_avatar)return `<img class="chat-avatar" src="${userAvatarUrl(user.username)}" alt="${esc(chatUserLabel(user))}">`;return `<span class="chat-avatar chat-avatar-placeholder">${esc(chatInitials(user))}</span>`}
function renderChatThreads(){const query=$('#chatSearch').value.trim().toLocaleLowerCase('uk-UA'),items=chatThreads.filter(chat=>chatTitle(chat).toLocaleLowerCase('uk-UA').includes(query));$('#chatThreadList').innerHTML=items.length?items.map(chat=>{const peers=(chat.members||[]).filter(user=>user.username!==currentAuthUser),peer=peers[0],online=peers.some(user=>user.online);return `<button type="button" class="chat-thread ${chat.id===activeChatId?'active':''}" data-chat-id="${chat.id}"><span class="chat-avatar-wrap">${chatAvatar(peer,Boolean(chat.is_group))}<i class="presence-dot ${online?'online':'offline'}"></i></span><span><strong>${esc(chatTitle(chat))}</strong><small>${esc(chat.last_body||'Повідомлень ще немає')}</small></span>${chat.unread_count?`<b>${chat.unread_count}</b>`:''}</button>`}).join(''):'<p class="chat-empty">Чатів поки немає.</p>';$$('.chat-thread').forEach(button=>button.onclick=()=>openChat(Number(button.dataset.chatId)))}
function renderChatMessages(){const chat=chatThreads.find(item=>item.id===activeChatId);if(!chat)return;$('#chatTitle').textContent=chatTitle(chat);$('#chatMembers').textContent=(chat.members||[]).map(user=>`${chatUserLabel(user)} · ${chatPresence(user)}`).join(' · ');$('#chatComposer').hidden=false;$('#chatMessages').innerHTML=chatMessages.length?chatMessages.map(message=>{const own=message.sender_username===currentAuthUser,sender=(chat.members||[]).find(user=>user.username===message.sender_username)||{username:message.sender_username},attachment=(message.attachments||[]).map(file=>`<a class="chat-file" href="${API}/chats/attachments/${file.id}" download>📎 ${esc(file.filename)} <small>${Math.ceil(file.size/1024)} КБ</small></a>`).join(''),submission=message.submission?`<a class="chat-application-card" href="?view=applications&submission_id=${encodeURIComponent(message.submission.id)}"><strong>Заявка ${esc(message.submission.id)}</strong><span>${esc(message.submission.supplier_name||'')} ${message.submission.supplier_code?`· ${esc(message.submission.supplier_code)}`:''}</span><small>${esc(message.submission.framework_pretty_id||'')} · Відкрити в реєстрі →</small></a>`:'',delivery=own?`<span class="chat-delivery ${message.read_by_all?'read':'sent'}">${message.read_by_all?'✓✓ Прочитано':'✓ Відправлено'}</span>`:'';return `<div class="chat-message-row ${own?'own':''}">${chatAvatar(sender)}<article class="chat-message ${own?'own':''}"><header><strong>${own?'Ви':esc(chatUserLabel(sender))}</strong><time>${esc(displayDate(message.created_at))}</time></header>${message.body?`<p>${esc(message.body).replaceAll('\n','<br>')}</p>`:''}${submission}${attachment}<footer>${delivery}</footer></article></div>`}).join(''):'<p class="chat-empty">Почніть розмову першим повідомленням.</p>';const box=$('#chatMessages');box.scrollTop=box.scrollHeight}
async function loadChats(silent=false){try{const data=await request(`${API}/chats?t=${Date.now()}`),incoming=data.items||[];if(chatNotificationReady)incoming.forEach(chat=>{const previous=chatUnreadState.get(chat.id)||0,current=Number(chat.unread_count||0);if(current>previous&&chat.last_sender!==currentAuthUser)notifyNewChatMessage(chat)});incoming.forEach(chat=>chatUnreadState.set(chat.id,Number(chat.unread_count||0)));chatNotificationReady=true;chatThreads=incoming;const badge=$('#messagesUnreadBadge'),count=Number(data.unread||0);badge.textContent=count;badge.hidden=!count;renderChatThreads();if(activeModule==='messages'&&activeChatId&&chatThreads.some(chat=>chat.id===activeChatId))await loadChatMessages(silent)}catch(error){if(!silent)toast(error.message)}}
async function loadChatMessages(silent=false){if(!activeChatId)return;try{const data=await request(`${API}/chats/${activeChatId}/messages?t=${Date.now()}`);chatMessages=data.items||[];renderChatMessages();await request(`${API}/chats/${activeChatId}/read`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const chat=chatThreads.find(item=>item.id===activeChatId);if(chat)chat.unread_count=0;renderChatThreads()}catch(error){if(!silent)toast(error.message)}}
async function openChat(id){activeChatId=id;renderChatThreads();await loadChatMessages();clearInterval(chatPollTimer);chatPollTimer=setInterval(()=>{if(activeModule==='messages')loadChats(true)},10000)}
function renderChatUserPicker(){const query=$('#newChatUserSearch').value.trim().toLocaleLowerCase('uk-UA');$('#newChatUsers').innerHTML=chatUsers.filter(user=>user.username!==currentAuthUser&&`${user.display_name} ${user.username}`.toLocaleLowerCase('uk-UA').includes(query)).map(user=>`<label><input type="checkbox" value="${esc(user.username)}"><span class="presence-dot ${user.online?'online':'offline'}"></span><span><strong>${esc(chatUserLabel(user))}</strong><small>${esc(user.username)} · ${esc(chatPresence(user))}</small></span></label>`).join('')||'<p class="chat-empty">Користувачів не знайдено.</p>'}
$('#messagesNav').onclick=()=>showModule('messages');$('#chatSearch').oninput=renderChatThreads;$('#newChatUserSearch').oninput=renderChatUserPicker;
$('#newChatBtn').onclick=async()=>{try{chatUsers=(await request(`${API}/chats/users?t=${Date.now()}`)).items||[];$('#newChatTitle').value=$('#newChatUserSearch').value='';renderChatUserPicker();$('#newChatDialog').showModal()}catch(error){toast(error.message)}};
$('#newChatForm').onsubmit=async event=>{event.preventDefault();const members=$$('#newChatUsers input:checked').map(input=>input.value);try{const data=await request(`${API}/chats`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('#newChatTitle').value,members})});$('#newChatDialog').close();await loadChats();await openChat(data.id);toast(data.existing?'Особистий чат уже існує':'Чат створено')}catch(error){toast(error.message)}};
$('#chatAttachBtn').onclick=()=>$('#chatAttachmentInput').click();$('#chatAttachmentInput').onchange=event=>{const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){event.target.value='';return toast('Максимальний розмір файла — 5 МБ')}chatAttachment=file;$('#chatAttachmentPreview').hidden=false;$('#chatAttachmentPreview').innerHTML=`<span>📎 ${esc(file.name)}</span><button type="button" class="ghost">×</button>`;$('#chatAttachmentPreview button').onclick=()=>{chatAttachment=null;event.target.value='';$('#chatAttachmentPreview').hidden=true}};
async function filePayload(file){if(!file)return null;const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return {filename:file.name,content_type:file.type||'application/octet-stream',content:btoa(binary)}}
$('#chatComposer').onsubmit=async event=>{event.preventDefault();const input=$('#chatMessageInput'),body=input.value.trim();if(!body&&!chatAttachment)return;try{const attachment=await filePayload(chatAttachment);await request(`${API}/chats/${activeChatId}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body,attachment})});input.value='';chatAttachment=null;$('#chatAttachmentInput').value='';$('#chatAttachmentPreview').hidden=true;await loadChats()}catch(error){toast(error.message)}};
$('#shareApplicationBtn').onclick=async()=>{const row=rows.find(item=>selected.has(item.id));if(!row)return;await loadChats();if(!chatThreads.length)return toast('Спочатку створіть чат у розділі «Повідомлення»');$('#shareApplicationSummary').textContent=`${row.participant} · ${row.id}`;$('#shareApplicationChat').innerHTML=chatThreads.map(chat=>`<option value="${chat.id}">${esc(chatTitle(chat))}</option>`).join('');$('#shareApplicationComment').value='';$('#shareApplicationDialog').dataset.submissionId=row.id;$('#shareApplicationDialog').showModal()};
$('#shareApplicationForm').onsubmit=async event=>{event.preventDefault();const dialog=$('#shareApplicationDialog'),chatId=Number($('#shareApplicationChat').value);try{await request(`${API}/chats/${chatId}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:$('#shareApplicationComment').value,submission_id:dialog.dataset.submissionId})});dialog.close();toast('Заявку надіслано в чат');await loadChats(true)}catch(error){toast(error.message)}};
setInterval(()=>loadChats(true),30000);
authReady.then(me=>{if(me)loadChats(true)});
$('#shareApplicationBtn').disabled=selected.size!==1;
