(function(){
  let overrides={},draft=[],customItems=[];
  const modes={text:'Текст',icon:'Іконка','icon-text':'Іконка + текст'};
  const config=()=>window.PQM_NAVIGATION_CONFIG||[],icons=()=>window.PQM_NAV_ICON_LIBRARY||{};
  const resolve=value=>config().map(item=>({...item,...(value[item.id]||{})})).sort((a,b)=>a.order-b.order);
  const canSee=item=>item.visible!==false&&(!item.permission||(item.permission==='role:admin'?currentMe?.role==='admin':Boolean(currentMe?.permissions?.[item.permission])));
  function previewButton(item){const icon=icons()[item.iconKey]||'<span class="nav-icon-slot"></span>';return `<button type="button" class="${item.displayMode==='icon'?'main-nav-icon':item.displayMode==='icon-text'?'main-nav-icon-text':'main-nav-text'}" title="${esc(item.tooltip)}" aria-label="${esc(item.label)}">${item.displayMode==='text'?esc(item.label):item.displayMode==='icon'?icon:`${icon}<span>${esc(item.label)}</span>`}</button>`}
  function renderPreview(){const box=$('#navigationPreview');if(box)box.innerHTML=draft.filter(canSee).sort((a,b)=>a.order-b.order).map(previewButton).join('')}
  function renderEditor(){
    if(currentMe?.role!=='admin')return;
    const panel=$('#adminNavigationPanel');panel.innerHTML=`<section class="card navigation-editor"><header><div><h2>Навігація</h2><p class="muted">Глобальне оформлення navbar. Routes і permissions не редагуються.</p></div></header><details class="navigation-icon-library"><summary>Бібліотека SVG-іконок</summary><div class="navigation-icon-form"><label>Назва<input id="navigationIconName" maxlength="80"></label><label>Ключ<input id="navigationIconKey" maxlength="40" placeholder="my_icon"></label><label class="navigation-icon-svg">SVG<textarea id="navigationIconSvg" rows="5" placeholder="<svg viewBox=&quot;0 0 24 24&quot;>…</svg>"></textarea><input id="navigationIconFile" type="file" accept=".svg,image/svg+xml"></label><div id="navigationIconPreview" class="navigation-icon-preview">Попередній перегляд</div><button id="navigationIconSave" type="button" class="primary">Зберегти іконку</button></div></details><div id="navigationEditorRows"></div><h3>Попередній перегляд</h3><div id="navigationPreview" class="navigation-preview"></div><footer><button id="navigationReset" type="button" class="ghost">Відновити стандартні налаштування</button><span></span><button id="navigationSave" type="button" class="primary">Зберегти навігацію</button></footer></section>`;
    const keys=Object.keys(icons());
    $('#navigationEditorRows').innerHTML=draft.sort((a,b)=>a.order-b.order).map(item=>`<div class="navigation-editor-row" data-nav-edit="${esc(item.id)}"><strong>${esc(item.label)}</strong><span class="navigation-current-icon">${icons()[item.iconKey]||'—'}</span><label>Іконка<select data-nav-icon>${keys.map(key=>`<option value="${key}" ${key===item.iconKey?'selected':''}>${key}</option>`).join('')}</select></label><label>Режим<select data-nav-mode>${Object.entries(modes).map(([key,label])=>`<option value="${key}" ${key===item.displayMode?'selected':''}>${label}</option>`).join('')}</select></label><label>Порядок<input data-nav-order type="number" min="1" max="99" value="${item.order}"></label><label class="navigation-visible"><input data-nav-visible type="checkbox" ${item.visible!==false?'checked':''}> Показувати</label><span class="navigation-move"><button type="button" data-nav-up aria-label="Вище">↑</button><button type="button" data-nav-down aria-label="Нижче">↓</button></span><span class="navigation-item-preview">${previewButton(item)}</span></div>`).join('');
    $('#navigationEditorRows').onchange=event=>{const row=event.target.closest('[data-nav-edit]'),item=draft.find(x=>x.id===row?.dataset.navEdit);if(!item)return;if(event.target.matches('[data-nav-icon]'))item.iconKey=event.target.value;if(event.target.matches('[data-nav-mode]'))item.displayMode=event.target.value;if(event.target.matches('[data-nav-order]'))item.order=Number(event.target.value);if(event.target.matches('[data-nav-visible]'))item.visible=event.target.checked;renderEditor()};
    $('#navigationEditorRows').onclick=event=>{const row=event.target.closest('[data-nav-edit]'),index=draft.findIndex(x=>x.id===row?.dataset.navEdit),delta=event.target.closest('[data-nav-up]')?-1:event.target.closest('[data-nav-down]')?1:0;if(!delta||index<0)return;const other=index+delta;if(other<0||other>=draft.length)return;[draft[index].order,draft[other].order]=[draft[other].order,draft[index].order];renderEditor()};
    const svgInput=$('#navigationIconSvg');
    svgInput.closest('label').insertAdjacentHTML('beforebegin',`<label>Кольори<select id="navigationIconColorMode"><option value="original">Зберегти оригінальні кольори</option><option value="currentColor">Використовувати колір інтерфейсу / currentColor</option></select></label><label>Редагувати власну іконку<select id="navigationIconExisting"><option value="">Нова іконка</option>${customItems.map(x=>`<option value="${esc(x.icon_key)}">${esc(x.name)}</option>`).join('')}</select></label>`);
    let previewVersion=0,previewTimer;
    svgInput.oninput=()=>{const version=++previewVersion;clearTimeout(previewTimer);$('#navigationIconPreview').textContent=svgInput.value.trim()?'Перевірка SVG…':'Попередній перегляд';if(!svgInput.value.trim())return;
      previewTimer=setTimeout(async()=>{try{const result=await request(`${API}/admin/navigation-icons/preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({svg:svgInput.value,color_mode:$('#navigationIconColorMode').value})});if(version===previewVersion)$('#navigationIconPreview').innerHTML=result.svg}catch(error){if(version===previewVersion)$('#navigationIconPreview').textContent=error.message}},250)};
    $('#navigationIconColorMode').onchange=svgInput.oninput;
    $('#navigationIconExisting').onchange=event=>{const item=customItems.find(x=>x.icon_key===event.target.value);if(!item)return;$('#navigationIconName').value=item.name;$('#navigationIconKey').value=item.icon_key;svgInput.value=item.source_svg;$('#navigationIconColorMode').value=item.color_mode;svgInput.oninput()};
    $('#navigationIconFile').onchange=async event=>{const file=event.target.files?.[0];if(file){svgInput.value=await file.text();svgInput.oninput()}};
    $('#navigationIconSave').onclick=saveIcon;$('#navigationSave').onclick=save;$('#navigationReset').onclick=()=>$('#navigationResetDialog').showModal();renderPreview();
  }
  function payload(){const out={};for(const item of draft)out[item.id]={iconKey:item.iconKey,displayMode:item.displayMode,order:item.order,visible:item.visible!==false};return out}
  async function save(){if(new Set(draft.map(x=>x.order)).size!==draft.length)return toast('Порядок пунктів не може дублюватися','error');try{const data=await request(`${API}/admin/navigation-settings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({overrides:payload()})});overrides=data.overrides||{};window.pqmRenderNavigation(overrides);window.pqmApplyNavigationAccess(currentMe);draft=resolve(overrides);renderEditor();toast('Глобальну навігацію збережено','success')}catch(error){toast(error.message,'error')}}
  async function reset(){try{const data=await request(`${API}/admin/navigation-settings`,{method:'DELETE'});overrides=data.overrides||{};window.pqmRenderNavigation(overrides);window.pqmApplyNavigationAccess(currentMe);draft=resolve(overrides);$('#navigationResetDialog').close();renderEditor();toast('Стандартну навігацію відновлено','success')}catch(error){toast(error.message,'error')}}
  async function saveIcon(){try{const saved=await request(`${API}/admin/navigation-icons`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#navigationIconName').value,icon_key:$('#navigationIconKey').value,svg:$('#navigationIconSvg').value,color_mode:$('#navigationIconColorMode').value})});await loadGlobal();renderEditor();$('#navigationIconPreview').innerHTML=saved.svg;toast('SVG-іконку збережено','success')}catch(error){toast(error.message,'error')}}
  async function loadGlobal(){try{const [data,library]=await Promise.all([request(`${API}/navigation-settings`),request(`${API}/navigation-icons`)]);customItems=library.items||[];window.pqmSetNavigationIcons(customItems);overrides=data.overrides||{};window.pqmRenderNavigation(overrides);if(currentMe)window.pqmApplyNavigationAccess(currentMe);draft=resolve(overrides)}catch(error){console.warn('Navigation settings unavailable',error)}}
  window.loadNavigationEditor=async()=>{if(currentMe?.role!=='admin')return;await loadGlobal();renderEditor()};
  $('#navigationResetConfirm').onclick=reset;
  loadGlobal();
})();
