-- Additive Block 3 migration. No existing PQM data is rebuilt or replaced.
CREATE TABLE IF NOT EXISTS operational_tasks (id TEXT PRIMARY KEY,task_key TEXT NOT NULL UNIQUE,task_type TEXT NOT NULL,supplier_code TEXT NOT NULL,supplier_name_snapshot TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'new',priority TEXT NOT NULL DEFAULT 'normal',assigned_officer_id INTEGER REFERENCES authorized_officers(id),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,due_at TEXT,ready_for_document_at TEXT,protocol_number TEXT DEFAULT '',protocol_date TEXT DEFAULT '',protocol_reference TEXT DEFAULT '',published_at TEXT,published_reference TEXT DEFAULT '',resolved_at TEXT,resolved_by TEXT,resolution_code TEXT DEFAULT '',resolution_text TEXT DEFAULT '',source_context TEXT NOT NULL DEFAULT '{}',document_context TEXT NOT NULL DEFAULT '{}',metadata TEXT NOT NULL DEFAULT '{}',version INTEGER NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS ix_operational_tasks_state ON operational_tasks(status,task_type);
CREATE INDEX IF NOT EXISTS ix_operational_tasks_supplier ON operational_tasks(supplier_code,created_at);
CREATE INDEX IF NOT EXISTS ix_operational_tasks_officer ON operational_tasks(assigned_officer_id,status);
CREATE TABLE IF NOT EXISTS operational_task_applications (task_id TEXT NOT NULL REFERENCES operational_tasks(id) ON DELETE CASCADE,application_id TEXT NOT NULL REFERENCES submissions(id),relation_type TEXT NOT NULL,PRIMARY KEY(task_id,application_id,relation_type));
CREATE TABLE IF NOT EXISTS operational_task_warnings (task_id TEXT NOT NULL REFERENCES operational_tasks(id) ON DELETE CASCADE,violation_report_id TEXT NOT NULL REFERENCES violation_reports(id),warning_date TEXT NOT NULL,sequence_no INTEGER NOT NULL,PRIMARY KEY(task_id,violation_report_id));
CREATE INDEX IF NOT EXISTS ix_operational_task_warnings_report ON operational_task_warnings(violation_report_id);
CREATE TABLE IF NOT EXISTS operational_task_amcu_decisions (task_id TEXT NOT NULL REFERENCES operational_tasks(id) ON DELETE CASCADE,amcu_decision_id TEXT NOT NULL REFERENCES amcu_registry(row_key),extract_url TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,updated_by TEXT NOT NULL,PRIMARY KEY(task_id,amcu_decision_id));
CREATE TABLE IF NOT EXISTS operational_task_events (id INTEGER PRIMARY KEY AUTOINCREMENT,task_id TEXT NOT NULL REFERENCES operational_tasks(id) ON DELETE CASCADE,event_type TEXT NOT NULL,created_at TEXT NOT NULL,actor TEXT NOT NULL,old_value TEXT,new_value TEXT,metadata TEXT NOT NULL DEFAULT '{}');
CREATE INDEX IF NOT EXISTS ix_operational_task_events ON operational_task_events(task_id,created_at,id);
