const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const src=fs.readFileSync('app.js','utf8');
const helper=src.slice(src.indexOf('const requestsRefreshState='),src.indexOf('function applyRoleCapabilities(me){'));
assert(helper.startsWith('const requestsRefreshState='));
const button={disabled:true,title:''};
const context={$:selector=>selector==='#requestsRefresh'?button:null,currentMe:{permissions:{'appeals.update':true}}};
vm.createContext(context);
vm.runInContext(helper,context);
const update=change=>vm.runInContext(`updateRequestsRefreshAvailability(${JSON.stringify(change)})`,context);
const check=(name,disabled)=>assert.strictEqual(button.disabled,disabled,name);
update({runtimeLoaded:true,running:false});
check('authorized admin, idle',false);
update({running:true});check('sync running',true);
update({running:false});check('sync complete',false);
update({starting:true});check('start request in flight',true);
update({starting:false});check('start request complete',false);
context.currentMe={role:'viewer',permissions:{'appeals.update':false}};
update();check('viewer cannot refresh',true);
context.currentMe={role:'admin',permissions:{'appeals.update':false}};
update();check('admin without appeals.update cannot refresh',true);
context.currentMe={role:'admin',permissions:{'appeals.update':true}};
update({runtimeLoaded:false});check('runtime features unavailable fails closed',true);
assert(src.includes('updateRequestsRefreshAvailability({running:Boolean(sync.running),starting:false});'));
const runtimeLoader=src.slice(src.indexOf('async function loadRuntimeFeatures(){'),src.indexOf("document.addEventListener('click',event=>{",src.indexOf('async function loadRuntimeFeatures(){')));
assert(runtimeLoader.includes('const features=await request(`${API}/runtime-features`);'));
assert(/updateRequestsRefreshAvailability\(\{runtimeLoaded:true,\s*sandboxMode:Boolean\(features\.sandbox_mode\),\s*sandboxOperational:Boolean\(features\.sandbox_operational\),\s*sandboxProzorroRead:Boolean\(features\.sandbox_prozorro_read\)\}\)/.test(runtimeLoader));
update({runtimeLoaded:true,sandboxMode:true,sandboxOperational:false,sandboxProzorroRead:true});
check('sandbox without operational approval cannot refresh',true);
update({sandboxOperational:true,sandboxProzorroRead:false});
check('sandbox without Prozorro read approval cannot refresh',true);
update({sandboxProzorroRead:true});
check('sandbox with both approvals can refresh',false);
update({sandboxMode:false,sandboxOperational:false,sandboxProzorroRead:false});
check('production does not inherit sandbox restrictions',false);
assert(/updateRequestsRefreshAvailability\(\);\r?\n  document\.body\.classList\.toggle/.test(src));
assert(!src.includes("$('#requestsRefresh').disabled="));
console.log('PASS: appeals refresh RBAC, running/completed, and one canonical button state');
