const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const src=fs.readFileSync('app.js','utf8');
const helper=src.slice(src.indexOf('const requestsRefreshState='),src.indexOf('function applyRoleCapabilities(me){'));
assert(helper.startsWith('const requestsRefreshState='));
const button={disabled:true,title:''};
const context={$:selector=>selector==='#requestsRefresh'?button:null,currentMe:{permissions:{'appeals.update':true}}};
vm.createContext(context);
vm.runInContext(helper,context);
const update=change=>vm.runInContext(`updateRequestsRefreshAvailability(${JSON.stringify(change)})`,context);
const check=(name,disabled)=>assert.strictEqual(button.disabled,disabled,name);
update({runtimeLoaded:true,sandboxMode:true,sandboxOperational:true,sandboxProzorroRead:true,running:false});
check('admin with both opt-ins, idle',false);
update({running:true});check('sync running',true);
update({running:false});check('sync complete',false);
update({starting:true});check('start request in flight',true);
update({starting:false});check('start request complete',false);
context.currentMe={role:'viewer',permissions:{'appeals.update':false}};
update();check('viewer cannot refresh',true);
context.currentMe={role:'admin',permissions:{'appeals.update':false}};
update();check('admin without appeals.update cannot refresh',true);
context.currentMe={role:'admin',permissions:{'appeals.update':true}};
update({sandboxOperational:false});check('operational opt-in missing',true);
update({sandboxOperational:true,sandboxProzorroRead:false});check('Prozorro read opt-in missing',true);
update({sandboxProzorroRead:true});check('opt-ins restored',false);
update({runtimeLoaded:false});check('runtime features unavailable fails closed',true);
assert(src.includes('updateRequestsRefreshAvailability({running:Boolean(sync.running),starting:false});'));
assert(src.includes('updateRequestsRefreshAvailability({runtimeLoaded:true,sandboxMode:Boolean(features.sandbox_mode)'));
assert(src.includes('updateRequestsRefreshAvailability();\n  document.body.classList.toggle'));
assert(!src.includes("$('#requestsRefresh').disabled="));
assert(!src.includes("'#requestsRefresh':features.sandbox_operational"));
console.log('PASS: appeals refresh RBAC, SANDBOX opt-ins, running/completed, and one canonical button state');
